@startuml
'https://plantuml.com/use-case-diagram



Użytkownik --> (Osiągnięcie jak najbardziej wyrównanej walki)





note right of (Osiągnięcie jak najbardziej wyrównanej walki)
Aby zadanie (przypadek użycia)
zostało zrealizowane, na końcu symulacji
musi pozostać tylko jedna jednostka
na mapie
end note

(Osiągnięcie jak najbardziej wyrównanej walki) -.> (Pozostawienie na mapie tylko jednej jednostki\n na końcu symulacji)
(Osiągnięcie jak najbardziej wyrównanej walki) -.> (Dobranie odpowiednich parametrów\n obu armii)
@enduml